name: Executar script para processar dados coletados

on:
  push:  
    branches: ["main"]
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"
          
      - name: checkout repo content
        uses: actions/checkout@v3
        
      - name: execute pwsh script formatar dados em js
        if: success()
        shell: pwsh
        run: ./scripts/processar-dados.ps1
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
